indexing-settings:
  sites: # формат url без слеша на конце
    - url: http://akvagaz.ru # 1 сек, страниц 53
      name: Аквагаз
#    - url: https://www.svetlovka.ru # 10 сек, страниц 236
#      name: Библиотека Светловка
    - url: https://radiomv0.ru # 176 сек, страниц 172 (с задержкой 1500мс)
      name: Милицейская волна
#    - url: https://playback.ru # 144 сек, страниц 2078
#      name: PlayBack.Ru
#    - url: https://dombulgakova.ru # 147 сек, страниц 529, (поменять userAgent, иногда ввести задержку)
#      name: Дом Булгакова
#    - url: https://ipfran.ru # 330 сек, страниц 1046
#      name: ИПФ РАН
#    - url: https://volochek.life # 2652 сек, страниц 5275 (с задержкой 100мс)
#      name: Вышний Волочек
#    - url: https://skillbox.ru # ??? сек, страниц 10925+ и `Java heap space`...
#      name: Skillbox
#    - url: https://lenta.ru # ??? сек, страниц 28732+ и `StackOverflowError`...
#      name: Лента.ру

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: My138753Kblth+
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
#      connection: # если `Unable to commit against JDBC Connection`
#        handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED # нужно при использовании Spring Boot v.3.0 и выше
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect # теперь не нужно по умолчанию
#    open-in-view: # настроить при необходимости

server:
  port: 8080

logging:
  level:
    root: info
